version: '3.7'
services:
  cowproxy:
    build: .
    image: cow-proxy:1
    container_name: cowproxy
    ports:
      - "8676:7777"
    volumes:
      - "./config-file:/root/.cow/rc"
    restart: unless-stopped
